sudo: required
language: generic
services:
- docker
env:
- HHVM_VERSION=latest
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.travis.sh
notifications:
  slack:
    secure: Yg5dyDlTAYc+tFYIzNlChbG96X5et3C0VP/wRIhTAvpEbJ6pbJr0f3bCJooO2oL1KGwZiQL0A27zOO2fha2abLywZDDTVqjncwKQ5HKQQRC/9xtZKWsKQvFwYTu78q2nZ/tt08s3P/St+ouiPmp6D1Xg1vu3XLG00efUU4aR3vM=
